DROP SCHEMA IF EXISTS `cst_339`;
CREATE SCHEMA IF NOT EXISTS `cst_339` DEFAULT CHARACTER SET utf8;
USE `cst_339`;
DROP TABLE IF EXISTS `cst_339`.`User`;
CREATE TABLE IF NOT EXISTS `cst_339`.`User` (
  `UserID` INT(15) NOT NULL,
  `Username` VARCHAR(50) NOT NULL,
  `UserPassword` VARCHAR(50) NOT NULL,
  `UserFName` VARCHAR(50) NOT NULL,
  `UserLName` VARCHAR(50) NOT NULL,
  `UserEmail` VARCHAR(50) NOT NULL,
  `UserPhone` INT(15) NOT NULL,
  PRIMARY KEY (`UserID`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8;